services:
    app.activity.listener:
        class: AppBundle\EventListener\AppListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    doctrine_event_listener:
        class: AppBundle\EventListener\DoctrineListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    component_converter:
        class: ApiBundle\Request\ParamConverter\ComponentConverter
        arguments: ['@service_container']
        tags:
            - { name: request.param_converter, priority: -2, converter: component_converter }

    nasa_provider:
        alias: app.nasa_provider

    contact_manipulator:
        class: AppBundle\Service\Util\ContactManipulator
        arguments: ['@customer_manager']

    account_manager:
        class: AppBundle\Manager\AccountManager
        arguments: ['AppBundle\Entity\Customer', '@doctrine']

    category_manager:
        alias: sonata.classification.manager.category

    customer_manager:
        class: AppBundle\Manager\CustomerManager
        arguments: ['AppBundle\Entity\Customer', '@doctrine']

    extra_manager:
        class: AppBundle\Manager\ExtraManager
        arguments: ['AppBundle\Entity\Component\Extra', '@doctrine']

    level_manager:
        class: AppBundle\Manager\Pricing\LevelManager
        arguments: ['AppBundle\Entity\Pricing\Level', '@doctrine']

    memorial_manager:
        class: AppBundle\Manager\Pricing\MemorialManager
        arguments: ['AppBundle\Entity\Pricing\Memorial', '@doctrine']

    module_manager:
        class: AppBundle\Manager\ModuleManager
        arguments: ['AppBundle\Entity\Component\Module', '@doctrine']

    mppt_manager:
        class: AppBundle\Manager\MpptManager
        arguments: ['AppBundle\Entity\Project\MpptOperation', '@doctrine']

    notification_manager:
        class: AppBundle\Manager\NotificationManager
        arguments: ['AppBundle\Entity\Notification', '@doctrine']

    inverter_manager:
        class: AppBundle\Manager\InverterManager
        arguments: ['AppBundle\Entity\Component\Inverter', '@doctrine']

    order_manager:
        class: AppBundle\Manager\OrderManager
        arguments: ['AppBundle\Entity\Order\Order', '@doctrine']

    order_element_manager:
        class: AppBundle\Manager\OrderElementManager
        arguments: ['AppBundle\Entity\Order\Element', '@doctrine']

    order_message_manager:
        class: AppBundle\Manager\OrderMessageManager
        arguments: ['AppBundle\Entity\Order\Message', '@doctrine']

    parameter_manager:
        class: AppBundle\Manager\ParameterManager
        arguments: ['AppBundle\Entity\Parameter', '@doctrine']

    project_manager:
        class: AppBundle\Manager\ProjectManager
        arguments: ['AppBundle\Entity\Component\Project', '@doctrine']

    project_area_manager:
        class: AppBundle\Manager\ProjectAreaManager
        arguments: ['AppBundle\Entity\Component\ProjectArea', '@doctrine']

    project_extra_manager:
        class: AppBundle\Manager\ProjectExtraManager
        arguments: ['AppBundle\Entity\Component\ProjectExtra', '@doctrine']

    project_inverter_manager:
        class: AppBundle\Manager\ProjectInverterManager
        arguments: ['AppBundle\Entity\Component\ProjectInverter', '@doctrine']

    project_module_manager:
        class: AppBundle\Manager\ProjectModuleManager
        arguments: ['AppBundle\Entity\Component\ProjectModule', '@doctrine']

    project_string_box_manager:
        class: AppBundle\Manager\ProjectStringBoxManager
        arguments: ['AppBundle\Entity\Component\ProjectStringBox', '@doctrine']

    project_structure_manager:
        class: AppBundle\Manager\ProjectStructureManager
        arguments: ['AppBundle\Entity\Component\ProjectStructure', '@doctrine']

    project_variety_manager:
        class: AppBundle\Manager\ProjectVarietyManager
        arguments: ['AppBundle\Entity\Component\ProjectVariety', '@doctrine']

    range_manager:
        class: AppBundle\Manager\Pricing\RangeManager
        arguments: ['AppBundle\Entity\Pricing\Range', '@doctrine']

    string_box_manager:
        class: AppBundle\Manager\StringBoxManager
        arguments: ['AppBundle\Entity\Component\StringBox', '@doctrine']

    structure_manager:
        class: AppBundle\Manager\StructureManager
        arguments: ['AppBundle\Entity\Component\Structure', '@doctrine']

    maker_manager:
        class: AppBundle\Manager\MakerManager
        arguments: ['AppBundle\Entity\Component\Maker', '@doctrine']

    variety_manager:
        class: AppBundle\Manager\VarietyManager
        arguments: ['AppBundle\Entity\Component\Variety', '@doctrine']

    task_manager:
        class: AppBundle\Manager\TaskManager
        arguments: ['AppBundle\Entity\Task', '@doctrine']

    theme_manager:
        class: AppBundle\Manager\ThemeManager
        arguments: ['AppBundle\Entity\Theme', '@doctrine']

    member_manager:
        alias: customer_manager

    stock_product_manager:
        class: AppBundle\Manager\Stock\ProductManager
        arguments: ['AppBundle\Entity\Stock\Product', '@doctrine']

    # Services
    component_collector:
        class: AppBundle\Service\Order\ComponentCollector
        arguments: ['@service_container']

    inverter_combinator:
        class: AppBundle\Service\InverterCombinator\InverterCombinator
        arguments: ['@inverter_manager']

    maker_detector:
        class: AppBundle\Service\ProjectGenerator\MakerDetector
        arguments: ['@inverter_manager']

    power_estimator:
        class: AppBundle\Service\PowerEstimator\PowerEstimator
        arguments: ['@nasa_provider']

    project_generator:
        class: AppBundle\Service\ProjectGenerator\ProjectGenerator
        arguments: ['@service_container']

    project_manipulator:
        class: AppBundle\Service\ProjectManipulator
        arguments: ['@project_manager']

    structure_calculator:
        class: AppBundle\Service\StructureCalculator\StructureCalculator
        arguments: ['@project_manager', '@structure_manager', '@project_structure_manager']

    string_box_calculator:
        class: AppBundle\Service\StringBoxCalculator\StringBoxCalculator
        arguments: ['@string_box_manager']

    notifier:
        class: AppBundle\Service\Notifier\Notifier

    component_file_handler:
        class: AppBundle\Service\Component\FileHandler
        arguments: ['@service_container']

    app_storage:
        alias: component_file_handler

    app_generator:
        alias: component_file_handler

    proposal_filter:
        class: AppBundle\Service\ProposalFilter
        arguments: ['@project_manager']

    order_transformer:
        class: AppBundle\Service\Order\OrderTransformer
        arguments: ['@order_manager']

    memorial_loader:
        class: AppBundle\Service\Pricing\MemorialLoader
        arguments: ['@memorial_manager']

    range_loader:
        class: AppBundle\Service\Pricing\RangeLoader
        arguments: ['@range_manager']

    order_precifier:
        class: AppBundle\Service\Order\OrderPrecifier
        arguments: ['@service_container']

    margin_manager:
        class: AppBundle\Entity\Component\PricingManager
        arguments: ['@parameter_manager', '@security.token_storage']

    project_precifier:
        class: AppBundle\Service\ProjectGenerator\Precifier
        arguments: ['@memorial_loader', '@range_loader', '@margin_manager']

    generator_checker:
        class: AppBundle\Service\ProjectGenerator\Checker\Checker
        arguments: ['@service_container']

    project_generator_type:
        class: AppBundle\Form\Component\GeneratorType
        arguments: ['@generator_checker']
        tags:
            - { name: form.type }

    entity_filter:
        class: AppBundle\Service\Filter\EntityFilter
        arguments: ['@doctrine.orm.entity_manager']

    generator_defaults:
        class: AppBundle\Service\ProjectGenerator\DefaultsResolver
        arguments: ['@entity_filter']

    access_voter:
        class: AppBundle\Service\Security\AccessVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    app_mailer:
        class: AppBundle\Service\Mailer
        arguments: ['@service_container']

    order_mailer:
        class: AppBundle\Service\Order\OrderMailer
        arguments: ['@service_container']

    range_normalizer:
        class: AppBundle\Service\Pricing\RangeNormalizer
        arguments: ['@range_manager']

    memorial_cloner:
        class: AppBundle\Service\Pricing\MemorialCloner
        arguments: ['@memorial_manager']

    order_manipulator:
        class: AppBundle\Service\Order\OrderManipulator

    order_finder:
        class: AppBundle\Service\Order\OrderFinder
        arguments: ['@order_manager']

    order_reference:
        class: AppBundle\Service\Order\OrderReference
        arguments: ['@order_manager', '@platform_counter']

    account_transfer:
        class: AppBundle\Service\Util\AccountTransfer
        arguments: ['@member_manager']

    platform_counter:
        class: AppBundle\Service\Util\PlatformCounter
        arguments: ['@parameter_manager']

    stock_provider:
        class: AppBundle\Service\Stock\Provider
        arguments: ['@service_container']

    stock_converter:
        class: AppBundle\Service\Stock\Converter
        arguments: ['@stock_provider']

    stock_control:
        class: AppBundle\Service\Stock\Control
        arguments: ['@stock_product_manager']

    stock_component:
        class: AppBundle\Service\Stock\Component
        arguments: ['@stock_provider']

    stock_query:
        class: AppBundle\Service\Stock\Query
        arguments: ['@stock_provider']

    order_stock:
        class: AppBundle\Service\Order\OrderStock
        arguments: ['@component_collector', '@stock_component']

    component_query:
        class: AppBundle\Service\Component\Query
        arguments: ['@service_container']
