#!/usr/bin/env bash

export SICES_PRODUCTION_PORT=443
export SICES_PRODUCTION_HOST='https://app.plataformasicessolar.com.br'
export SICES_PRODUCTION_URI='https://app.plataformasicessolar.com.br'
export SICES_PRODUCTION_DATABASE_NAME=sices_solar
export SICES_PRODUCTION_DATABASE_USER=mysqlproducao
export SICES_PRODUCTION_DATABASE_HOST='mysql-db-producao.crtwvzhue9fu.sa-east-1.rds.amazonaws.com'
export SICES_PRODUCTION_DATABASE_PORT=3306
export SICES_PRODUCTION_DATABASE_PASS='avCy8ZFhhg6rMnKstw'
export SICES_PRODUCTION_FTP_HOST='54.233.182.111'
export SICES_PRODUCTION_FTP_PORT=21
export SICES_PRODUCTION_FTP_USER=proceda_admin
export SICES_PRODUCTION_FTP_PASS='whJHVcRp6mhac8cnN6'
