knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        filter_field_name: filter_name
        filter_value_name: filter_value
        distinct: true
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig
        filtration: AppBundle:Pagination:filtration.html.twig

knp_menu:
    twig:
        template: AppBundle::menu.html.twig

knp_doctrine_behaviors:
    blameable: ~
    geocodable: ~
    loggable: ~
    sluggable: true
    soft_deletable: true
    timestampable: true

knp_snappy:
    pdf:
        enabled: true
        binary: %kernel.root_dir%/../web/helpers/wkhtmltox/bin/wkhtmltopdf
        options: []
    image:
        enabled: true
        binary: %kernel.root_dir%/../web/helpers/wkhtmltox/bin/wkhtmltoimage
        options: []
