fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    use_listener:           true
    use_flash_notifications: true
    use_username_form_type: true
    model_manager_name:     null
    from_email:
        address:        no-reply@inovadorsolar.com
        sender_name:    Inovador Solar
    profile:
        form:
            type:               FOS\UserBundle\Form\Type\ProfileFormType
            name:               fos_user_profile_form
            validation_groups:  [Profile, Default]
    change_password:
        form:
            type:               FOS\UserBundle\Form\Type\ChangePasswordFormType
            name:               fos_user_change_password_form
            validation_groups:  [ChangePassword, Default]
    registration:
        confirmation:
            from_email:
                address:        ...
                sender_name:    ...
            enabled:    false
            template:   FOSUserBundle:Registration:email.txt.twig
        form:
            type:               FOS\UserBundle\Form\Type\RegistrationFormType
            name:               fos_user_registration_form
            validation_groups:  [Registration, Default]
    resetting:
        token_ttl: 86400
        email:
            from_email:
                address:        no-reply@inovadorsolar.com
                sender_name:    Inovador Solar
            template:  FOSUserBundle:Resetting:email.html.twig
        form:
            type:               FOS\UserBundle\Form\Type\ResettingFormType
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword, Default]
    service:
        mailer:                 fos_user.mailer.twig_swift
        email_canonicalizer:    fos_user.util.canonicalizer.default
        username_canonicalizer: fos_user.util.canonicalizer.default
        token_generator:        fos_user.util.token_generator.default
        user_manager:           fos_user.user_manager.default

fos_oauth_server:
    db_driver: orm
    client_class:         ApiBundle\Entity\Client
    access_token_class:   ApiBundle\Entity\AccessToken
    auth_code_class:      ApiBundle\Entity\AuthCode
    refresh_token_class:  ApiBundle\Entity\RefreshToken
    service:
        user_provider:    fos_user.user_provider.username

fos_rest:
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    routing_loader:
        default_format:    json
    serializer:
        serialize_null:    true