nelmio_api_doc: ~

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_credentials: true
            allow_origin: ['CES_ISQUIK_PORT, CES_BUNDLE_PORT, CES_SICES_PORT']
            allow_headers: ['Content-Type, X-Requested-With']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['CES_ISQUIK_HOST']