services:
    app.authentication.success_handler:
        class: AppBundle\Service\Security\AuthenticationSuccessHandler
        arguments: ['@security.http_utils']

    app.authentication.failure_handler:
        class: AppBundle\Service\Security\AuthenticationFailureHandler
        arguments: ['@http_kernel', '@security.http_utils']

    app.activity.listener:
        class: AppBundle\EventListener\AppListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: doctrine.event_listener, event: postLoad }

    doctrine_event_listener:
        class: AppBundle\EventListener\DoctrineListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber, connection: default }


    # Manipulators
    contact_manipulator:
        class: AppBundle\Service\Util\ContactManipulator
        arguments: ['@app.customer_manager']

    # Managers
    account_manager:
        class: AppBundle\Manager\AccountManager
        arguments: ['AppBundle\Entity\Customer', '@doctrine']

    customer_manager:
        class: AppBundle\Manager\CustomerManager
        arguments: ['AppBundle\Entity\Customer', '@doctrine']

    module_manager:
        class: AppBundle\Manager\ModuleManager
        arguments: ['AppBundle\Entity\Component\Module', '@doctrine']

    mppt_manager:
        class: AppBundle\Manager\MpptManager
        arguments: ['AppBundle\Entity\Project\MpptOperation', '@doctrine']

    inverter_manager:
        class: AppBundle\Manager\InverterManager
        arguments: ['AppBundle\Entity\Component\Inverter', '@doctrine']

    project_manager:
        class: AppBundle\Manager\ProjectManager
        arguments: ['AppBundle\Entity\Component\Project', '@doctrine']

    project_area_manager:
        class: AppBundle\Manager\ProjectAreaManager
        arguments: ['AppBundle\Entity\Component\ProjectArea', '@doctrine']

    project_inverter_manager:
        class: AppBundle\Manager\ProjectInverterManager
        arguments: ['AppBundle\Entity\Component\ProjectInverter', '@doctrine']

    project_module_manager:
        class: AppBundle\Manager\ProjectModuleManager
        arguments: ['AppBundle\Entity\Component\ProjectModule', '@doctrine']

    structure_manager:
        class: AppBundle\Manager\StructureManager
        arguments: ['AppBundle\Entity\Component\Structure', '@doctrine']