services:
    app.activity.listener:
        class: AppBundle\EventListener\AppListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: doctrine.event_listener, event: postLoad }

    doctrine_event_listener:
        class: AppBundle\EventListener\DoctrineListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    # Aliased Services
    nasa_provider:
        alias: app.nasa_provider

    # Manipulators
    contact_manipulator:
        class: AppBundle\Service\Util\ContactManipulator
        arguments: ['@app.customer_manager']

    # Managers
    account_manager:
        class: AppBundle\Manager\AccountManager
        arguments: ['AppBundle\Entity\Customer', '@doctrine']

    category_manager:
        alias: sonata.classification.manager.category

    customer_manager:
        class: AppBundle\Manager\CustomerManager
        arguments: ['AppBundle\Entity\Customer', '@doctrine']

    extra_manager:
        class: AppBundle\Manager\ExtraManager
        arguments: ['AppBundle\Entity\Component\Extra', '@doctrine']

    level_manager:
        class: AppBundle\Manager\Pricing\LevelManager
        arguments: ['AppBundle\Entity\Pricing\Level', '@doctrine']

    memorial_manager:
        class: AppBundle\Manager\Pricing\MemorialManager
        arguments: ['AppBundle\Entity\Pricing\Memorial', '@doctrine']

    module_manager:
        class: AppBundle\Manager\ModuleManager
        arguments: ['AppBundle\Entity\Component\Module', '@doctrine']

    mppt_manager:
        class: AppBundle\Manager\MpptManager
        arguments: ['AppBundle\Entity\Project\MpptOperation', '@doctrine']

    inverter_manager:
        class: AppBundle\Manager\InverterManager
        arguments: ['AppBundle\Entity\Component\Inverter', '@doctrine']

    order_manager:
        class: AppBundle\Manager\OrderManager
        arguments: ['AppBundle\Entity\Order\Order', '@doctrine']

    order_element_manager:
        class: AppBundle\Manager\OrderElementManager
        arguments: ['AppBundle\Entity\Order\Element', '@doctrine']

    project_manager:
        class: AppBundle\Manager\ProjectManager
        arguments: ['AppBundle\Entity\Component\Project', '@doctrine']

    project_area_manager:
        class: AppBundle\Manager\ProjectAreaManager
        arguments: ['AppBundle\Entity\Component\ProjectArea', '@doctrine']

    project_extra_manager:
        class: AppBundle\Manager\ProjectExtraManager
        arguments: ['AppBundle\Entity\Component\ProjectExtra', '@doctrine']

    project_inverter_manager:
        class: AppBundle\Manager\ProjectInverterManager
        arguments: ['AppBundle\Entity\Component\ProjectInverter', '@doctrine']

    project_module_manager:
        class: AppBundle\Manager\ProjectModuleManager
        arguments: ['AppBundle\Entity\Component\ProjectModule', '@doctrine']

    project_string_box_manager:
        class: AppBundle\Manager\ProjectStringBoxManager
        arguments: ['AppBundle\Entity\Component\ProjectStringBox', '@doctrine']

    project_structure_manager:
        class: AppBundle\Manager\ProjectStructureManager
        arguments: ['AppBundle\Entity\Component\ProjectStructure', '@doctrine']

    project_variety_manager:
        class: AppBundle\Manager\ProjectVarietyManager
        arguments: ['AppBundle\Entity\Component\ProjectVariety', '@doctrine']

    range_manager:
        class: AppBundle\Manager\Pricing\RangeManager
        arguments: ['AppBundle\Entity\Pricing\Range', '@doctrine']

    string_box_manager:
        class: AppBundle\Manager\StringBoxManager
        arguments: ['AppBundle\Entity\Component\StringBox', '@doctrine']

    structure_manager:
        class: AppBundle\Manager\StructureManager
        arguments: ['AppBundle\Entity\Component\Structure', '@doctrine']

    maker_manager:
        class: AppBundle\Manager\MakerManager
        arguments: ['AppBundle\Entity\Component\Maker', '@doctrine']

    variety_manager:
        class: AppBundle\Manager\VarietyManager
        arguments: ['AppBundle\Entity\Component\Variety', '@doctrine']

    theme_manager:
        class: AppBundle\Manager\ThemeManager
        arguments: ['AppBundle\Entity\Theme', '@doctrine']

    # Services
    inverter_combinator:
        class: AppBundle\Service\InverterCombinator\InverterCombinator
        arguments: ['@inverter_manager']

    maker_detector:
        class: AppBundle\Service\ProjectGenerator\MakerDetector
        arguments: ['@inverter_manager']

    power_estimator:
        class: AppBundle\Service\PowerEstimator\PowerEstimator
        arguments: ['@nasa_provider']

    project_generator:
        class: AppBundle\Service\ProjectGenerator\ProjectGenerator
        arguments: ['@service_container']

    project_manipulator:
        class: AppBundle\Service\ProjectManipulator
        arguments: ['@project_manager']

    structure_calculator:
        class: AppBundle\Service\StructureCalculator\StructureCalculator
        arguments: ['@project_manager', '@structure_manager', '@project_structure_manager']

    string_box_calculator:
        class: AppBundle\Service\StringBoxCalculator\StringBoxCalculator
        arguments: ['@string_box_manager']

    notifier:
        class: AppBundle\Service\Notifier\Notifier

    component_file_handler:
        class: AppBundle\Service\Component\FileHandler
        arguments: ['%kernel.root_dir%/../web/uploads/components/']

    proposal_filter:
        class: AppBundle\Service\ProposalFilter
        arguments: ['@project_manager']

    order_transformer:
        class: AppBundle\Service\Order\OrderTransformer
        arguments: ['@order_manager']

    memorial_loader:
        class: AppBundle\Service\Pricing\MemorialLoader
        arguments: ['@memorial_manager']

    range_loader:
        class: AppBundle\Service\Pricing\RangeLoader
        arguments: ['@range_manager']

    order_precifier:
        class: AppBundle\Service\Order\OrderPrecifier
        arguments: ['@service_container']

    # Form Services
    project_generator_type:
        class: AppBundle\Form\Component\GeneratorType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    access_voter:
        class: AppBundle\Service\Security\AccessVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }