#!/usr/bin/env bash

export SICES_STAGING_PORT=80
export SICES_STAGING_IP=18.231.15.228
export SICES_STAGING_HOST="http://$SICES_STAGING_IP"
export SICES_STAGING_DATABASE_NAME=sices_solar
export SICES_STAGING_DATABASE_USER=mysqlproducao
export SICES_STAGING_DATABASE_HOST='mysql-db-producao.crtwvzhue9fu.sa-east-1.rds.amazonaws.com'
export SICES_STAGING_DATABASE_PORT=3306
export SICES_STAGING_DATABASE_PASS='avCy8ZFhhg6rMnKstw'
