#!/usr/bin/env bash

cd $SICES_PATH

if [ -z ${1+x} ] || [ $1 == '--development' ]; then
  FLAG=development
elif [ $1 == '--homolog' ]; then
  FLAG=homolog
else [ $1 == '--production' ];
  FLAG=production
fi

cp app/config/parameters-$FLAG.yml app/config/parameters.yml

if [ $FLAG == 'development' ]; then
  php app/console server:run
fi
