#!/usr/bin/env bash

cd $SICES_PATH

cli/ces-notify-slack --production-deploy-start

echo "Creating current version Backup..."
rsync -avzh /var/www/** /var/www/.backup

echo "Importing Temp files from homolog..."
rsync -azvv -e "ssh -i ~/.ssh/authorized_ssh" admin@54.233.150.10:/var/www/** /var/www/.temp

echo "Deploying files from Temp..."
rsync -avzh --delete /var/www/.temp/** /var/www/

source cli/ces-server-config --production

php app/console doctrine:schema:update --force
bundle/app/node_modules/.bin/pm2 restart 0

rm -rf app/cache/dev/**
rm -rf app/cache/prod/**

php app/console cache:clear --env=dev
php app/console cache:clear --env=prod

cli/ces-notify-slack --production-deploy-end

echo 'Done.'
