#!/usr/bin/env bash

cd $SICES_PATH

echo "Importing Sices development variables..."
source ces-variables-ci --development

if [ -z ${1+x} ] || [ $1 == '--development' ]; then

  bash $CLI_PATH/ces-app-install

  php app/console doctrine:schema:update --force
  echo "Sices Server starting on $CES_SICES_HOST:$CES_SICES_PORT"
  php app/console server:run &

  echo "Bundle App starting on $CES_BUNDLE_HOST:$CES_BUNDLE_PORT"
  node_modules/.bin/node-supervisor --harmony index.js &

  # Enable job control
  set -m

  while :
  do
    read input
    [[ $input == finish ]] && break

    # Run the command in background
    bash -c "$input" &

    # Move the command back-into foreground
    fg %- > /dev/null 2>&1;
  done
fi
