#!/usr/bin/env bash

cd $SICES_PATH

echo "Creating current version Backup..."
rsync -avzh /var/www/** /var/www/.backup

echo "Importing Temp files from homolog..."
rsync -azvv -e "ssh -i ~/.ssh/authorized_ssh" admin@54.233.150.10:/var/www/** /var/www/.temp

echo "Deploying files from Temp..."
rsync -avzh --delete /var/www/.temp/** /var/www/

echo 'Done.'
