#!/usr/bin/env bash

cd $SICES_PATH

echo 'Note: This process can be a little slow!'
chmod 600 devops/aws/homolog.pem

if [ -z ${1+x} ]; then
  echo 'Cloning homolog database... enter your mysql password:'
  read -s password
else
  password=$1
fi

homologDb="sices-homolog.sql"
compressedHomologDb="sices-homolog.tar.gz"

echo 'Downloading compressed homolog database...'
ssh -t -i devops/aws/homolog.pem admin@54.233.150.10 "mysqldump -h $SICES_HOMOLOG_DATABASE_HOST -P $SICES_HOMOLOG_DATABASE_PORT -u $SICES_HOMOLOG_DATABASE_USER -p$SICES_HOMOLOG_DATABASE_PASS $SICES_HOMOLOG_DATABASE_NAME > /var/www/.mirror/$homologDb" > /dev/null 2>&1
ssh -t -i devops/aws/homolog.pem admin@54.233.150.10 "cd /var/www/.mirror && tar -cvzf $compressedHomologDb $homologDb" > /dev/null 2>&1

mkdir .mirror
scp -i devops/aws/homolog.pem admin@54.233.150.10:/var/www/.mirror/$compressedHomologDb .mirror/$compressedHomologDb

echo 'Extracting compressed file to:'
cd .mirror
tar -xzvf $compressedHomologDb

echo 'Local exporting Database...'
mysql -u root -p$password sices_solar < $homologDb > /dev/null 2>&1

cd ../
rm -rf .mirror

echo 'Cleaning Cache...'
rm -rf app/cache/dev/**
rm -rf app/cache/prod/**

php app/console cache:clear --env=dev
php app/console cache:clear --env=prod

echo 'Updating local Database...'
php app/console doctrine:schema:update --force

echo 'Database mirror done.'
