#!/usr/bin/env bash

cd $SICES_PATH

if [ -z ${1+x} ] || [ $1 == '--development' ]; then

  cp cli/ces-pre-push .git/hooks/pre-push
  FLAG=development

elif [ $1 == '--homolog' ]; then

  echo "Sices starting bundle on port $BUNDLE_PORT"
  cd bundle/app
  yarn install
  node_modules/.bin/pm2 start index.js -n "homolog-bundle"
  FLAG=homolog

elif [ $1 == '--production' ]; then

  echo "Sices starting bundle on port $BUNDLE_PORT"
  cd bundle/app
  yarn install
  node_modules/.bin/pm2 start index.js -n "production-bundle"
  FLAG=production

elif [ $1 == '--test' ];

  FLAG=test

fi

echo 'Sices creating files...'
cp app/config/parameters_$FLAG.yml app/config/parameters.yml
cp app/config/config_sample.yml app/config/config.yml
touch web/deploy/deploy.log

echo 'Sices updating schema...'
php app/console doctrine:schema:update --force

echo 'Done.'
