#!/usr/bin/env bash

cd $SICES_PATH

echo "Importing Sices development variables..."
source ces-variables-ci --development

if [ -z ${1+x} ] || [ $1 == '--development' ]; then

  composer install
  php app/console doctrine:schema:update --force
  php app/console server:run &

  cd bundle/app
  yarn install
  node_modules/.bin/nodemon index.js &

  echo "Sices Server starting on $CES_SICES_HOST:$CES_SICES_PORT"
  echo "Bundle App starting on $CES_BUNDLE_HOST:$CES_BUNDLE_PORT"
  sensible-browser "http://sicessolar.dev:$CES_SICES_PORT"
  echo 'Done.'

  # Enable job control
  set -m

  while :
  do
    read input
    [[ $input == finish ]] && break

    # Run the command in background
    bash -c "$input" &

    # Move the command back-into foreground
    fg %-

  done

elif [ $1 == '--isquikmock' ]; then

  echo "Starting Bundle Test (Isquik Mock) on: $CES_ISQUIK_HOST:$CES_ISQUIK_PORT"
  cd bundle/test
  yarn install
  node_modules/.bin/nodemon index.js

  sensible-browser "$CES_ISQUIK_HOST:$CES_ISQUIK_PORT"

fi
