#!/usr/bin/env bash

cd $SICES_PATH

cli/ces-slack-notify 'Starting Homolog Deploy...'

git fetch origin
GIT_WORK_TREE=$SICES_PATH git checkout -f
git pull origin master -f

cli/ces-permission-fix
source cli/ces-variables-ci --homolog

composer install
cli/ces-bug-fix
php app/console doctrine:schema:update --force
bundles/isquik/node_modules/.bin/pm2 restart 0

cli/ces-frontend-compile
cli/ces-permission-fix

cli/ces-slack-notify 'Homolog Deploy Done!'
