#!/usr/bin/env bash

export PROJECT_ROOT=$SICES_PATH/backend
export PATH="$SICES_PATH/cli:$PATH"

export SICES_DEVELOPMENT_PORT=8000
export SICES_DEVELOPMENT_HOST='http://localhost'
export SICES_HOMOLOG_PORT=80
export SICES_HOMOLOG_HOST=54.233.150.10

export BUNDLE_DEVELOPMENT_PORT=2020
export BUNDLE_DEVELOPMENT_HOST='http://localhost'
export BUNDLE_HOMOLOG_PORT=3000
export BUNDLE_HOMOLOG_HOST=54.233.150.10

export ISQUIK_MOCK_PORT=2021
export ISQUIK_MOCK_HOST='http://localhost'
export ISQUIK_SERVER_PORT=2021
export ISQUIK_SERVER_HOST='http://localhost'
export ISQUIK_AUTH_KEY='AIzaSyCDKjcT0Rme97CLoZtA-WYKDdAch-yc2gQ'
export ISQUIK_AUTH_USER='sices.solar@sices.com.br'
export ISQUIK_AUTH_PASS='sices123@'
