#!/usr/bin/env bash

cd $SICES_PATH

homologDb="sices-homolog.sql"
compressedHomologDb="sices-homolog.tar.gz"

ssh -t -i devops/aws/homolog.pem admin@54.233.150.10 "mysqldump -h $SICES_HOMOLOG_DATABASE_HOST -P $SICES_HOMOLOG_DATABASE_PORT -u $SICES_HOMOLOG_DATABASE_USER -p$SICES_HOMOLOG_DATABASE_PASS $SICES_HOMOLOG_DATABASE_NAME > /var/www/.mirror/$homologDb"
ssh -t -i devops/aws/homolog.pem admin@54.233.150.10 "cd /var/www/.mirror && tar -cvzf $compressedHomologDb $homologDb"

mkdir .mirror
scp -i devops/aws/homolog.pem admin@54.233.150.10:/var/www/.mirror/$compressedHomologDb .mirror/$compressedHomologDb

cd .mirror
tar -xzvf $compressedHomologDb
mysql -u root -p sices_solar < $homologDb

cd ../
rm -rf .mirror

rm -rf app/cache/dev/**
rm -rf app/cache/prod/**

php app/console cache:clear --env=dev
php app/console cache:clear --env=prod

php app/console doctrine:schema:update --force
