#!/usr/bin/env bash

cd $SICES_PATH

if [ -z ${1+x} ] || [ $1 == '--development' ]; then

  cp $CLI_PATH/util/pre-push .git/hooks/pre-push
  bash $CLI_PATH/ces-database-config $1

elif [ $1 == '--homolog' ]; then

  FLAG=homolog

elif [ $1 == '--production' ]; then

  FLAG=production

fi

if [[ $FLAG == 'homolog' ]] || [[ $FLAG == 'production' ]]; then

  echo "Importing Sices $FLAG variables..."
  source cli/ces-variables-ci --$FLAG
  bash $CLI_PATH/ces-app-install

  # Remote automatic start Bundle App and Server
  echo "Sices starting Bundle App on: $CES_BUNDLE_HOST:$CES_BUNDLE_PORT"
  node_modules/.bin/pm2 start index.js --node-args="--harmony" -n "bundle"
  cd $SICES_PATH

  mkdir .temp
  mkdir .mirror
  mkdir .backup

  echo 'Creating params file...'
  cp app/config/parameters_$FLAG.yml app/config/parameters.yml

fi

echo 'Creating config file...'
cp app/config/config_sample.yml app/config/config.yml

touch web/deploy/deploy.log

echo 'Done.'
