#!/usr/bin/env bash

cd $SICES_PATH

if [[ -z $1 ]] || [[ $1 == '--help' ]] || [[ $1 == '-h' ]]; then
  printf "Initing new Task:

  Usage:

  ces-new-task issue-[NUMBER]

  Exemple:

  ces-new-task issue-3084\n"
  exit 0;
fi

issue_name=$1
result=$(git branch | grep $issue_name)
pull=0

git checkout master
git fetch origin
git pull origin master
git checkout -b $issue_name
echo "Done, now into Branch: $issue_name"
