#!/usr/bin/env bash

cd $SICES_PATH

echo "Importing Sices $1 variables..."
source cli/ces-variables-ci $1

bash $CLI_PATH/ces-app-install

if [ -z ${1+x} ] || [ $1 == '--development' ]; then

  php app/console doctrine:schema:update --force
  echo "Sices Server starting on $CES_SICES_HOST:$CES_SICES_PORT"
  php app/console server:run &

  echo "Bundle App starting on $CES_BUNDLE_HOST:$CES_BUNDLE_PORT"
  node_modules/.bin/node-supervisor --harmony index.js &

  # Enable job control
  set -m

  while :
  do
    read input
    [[ $input == finish ]] && break

    # Run the command in background
    bash -c "$input" &

    # Move the command back-into foreground
    fg %- > /dev/null 2>&1;
  done
fi

if [[ $1 == 'homolog' ]] || [[ $1 == 'production' ]]; then

  # Remote automatic start Bundle App and Server
  echo "Sices starting Bundle App on: $CES_BUNDLE_HOST:$CES_BUNDLE_PORT"
  node_modules/.bin/pm2 start index.js --node-args="--harmony" -n "bundle"

fi
