#!/usr/bin/env bash

cd $SICES_PATH

if [ $1 == '--homolog' ]; then

  bash $CLI_PATH/ces-slack-notify 'Starting Homolog Deploy...'

  bash $CLI_PATH/ces-app-clone --homolog
  bash $CLI_PATH/ces-permission-fix
  source bash $CLI_PATH/ces-variables-ci --homolog
  composer install
  bash $CLI_PATH/ces-bug-fix
  bash $CLI_PATH/ces-cache-clear
  bash $CLI_PATH/ces-database-update
  bundles/isquik/node_modules/.bin/pm2 restart 0
  bash $CLI_PATH/ces-frontend-compile
  bash $CLI_PATH/ces-permission-fix

  bash $CLI_PATH/ces-slack-notify 'Homolog Deploy Done!'

elif [ $1 == '--production' ]; then

  bash $CLI_PATH/ces-slack-notify 'Starting Production Deploy...'

  bash $CLI_PATH/ces-app-clone
  source $CLI_PATH/ces-app-config --production
  bash $CLI_PATH/ces-cache-clear
  bash $CLI_PATH/ces-database-update
  bundles/isquik/node_modules/.bin/pm2 restart 0

  bash $CLI_PATH/ces-slack-notify 'Production Deploy Done!'

fi

echo 'Done.'
