services:
    account_provider:
        class: ApiBundle\Provider\AccountProvider

    api_pager:
        class: ApiBundle\Common\Pager
        arguments: ['@api_formatter']

    api_handler:
        class: ApiBundle\Common\Handler
        arguments: ['@service_container']

    api_formatter:
        class: ApiBundle\Common\Formatter
        arguments: ['@serializer']