AppBundle\Entity\Component\Module:
    properties:
        code:
            - NotBlank:
                message: the field [code] cannot be null
                groups: api
                payload: 1600
        model:
            - NotBlank:
                message: The field [model] cannot null
                groups: api
                payload: 1610
AppBundle\Entity\Component\Inverter:
    properties:
        code:
            - NotBlank:
                message: the field [code] cannot be null
                groups: api
                payload: 1500
        model:
            - NotBlank:
                message: The field [model] cannot null
                groups: api
                payload: 1510
