services:
    # Managers

    cart_has_kit_manager:
        class: Ecommerce\Cart\Manager\CartHasKitManager
        arguments: ['Ecommerce\Cart\Entity\CartHasKit', '@doctrine']

    cart_manager:
        class: Ecommerce\Cart\Manager\CartManager
        arguments: ['Ecommerce\Cart\Entity\Cart', '@doctrine']

    # Services

    integrador.cart_service:
        class: Ecommerce\Cart\Service\Integrador\CartService
        arguments: ['@cart_manager', '@cart_has_kit_manager', '@kit_manager']

    integrador.cart_checkout_service:
        class: Ecommerce\Cart\Service\Integrador\CartCheckoutService
        arguments:
            - '@cart_manager'
            - '@integrador.cart_pool_helper'
            - '@integrador.cart_service'
            - '@cart_has_kit_manager'
            - '@parameter_manager'
