#!/usr/bin/env bash

cd $SICES_PATH

echo 'Fixing KNP Bug...'

path=backend/vendor/knplabs/knp-components/src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/Query

initial='$alias = reset($parts);'
final='$alias = trim(reset($parts));'

sed -i "s/$initial/$final/g" $path/WhereWalker.php

echo 'Fixing eslint-plugin-vue Bug...'

cat $CLI_PATH/util/src/eslint-plugin-vue.js \
  > $SICES_PATH/frontend/node_modules/eslint-plugin-vue/lib/utils/indent-common.js
