#!/usr/bin/env bash

cd $SICES_PATH

include_knp_wherewalker_phptrim() {
  local file=backend/vendor/knplabs/knp-components/src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/Query/WhereWalker.php

  sed -i 's/$alias = reset($parts);/$alias = trim(reset($parts));/g' $file
}

replace_eslintplugin_unmerged_indentcommon() {
  local file_input=$CLI_PATH/util/src/eslint-plugin-vue.js
  local file_output=$SICES_PATH/frontend/node_modules/eslint-plugin-vue/lib/utils/indent-common.js

  cat $file_input > $file_output
}

if [[ $1 = '--dependencies' ]]; then
  echo 'Fixing KNP Bug...'
  $(include_knp_wherewalker_phptrim)

  echo 'Fixing eslint-plugin-vue Bug...'
  $(replace_eslintplugin_unmerged_indentcommon)
fi
