#!/usr/bin/env bash

USER_CREDENTIALS=$(cat $CLI_PATH/stash/users | grep $1)

case ${2/--/} in
  'name')
    echo $USER_CREDENTIALS | awk -F$';' '{print $1}'
    ;;
  'github')
    echo $USER_CREDENTIALS | awk -F$';' '{print $2}'
    ;;
  'slack')
    echo $USER_CREDENTIALS | awk -F$';' '{print $3}'
    ;;
  'trello')
    echo $USER_CREDENTIALS | awk -F$';' '{print $4}'
    ;;
  'email')
    echo $USER_CREDENTIALS | awk -F$';' '{print $5}'
esac
