#!/usr/bin/env bash

get_type_index() {
  case ${1/--/} in
    'name')
      echo 1
      ;;
    'github')
      echo 2
      ;;
    'slack')
      echo 3
      ;;
    'trello')
      echo 4
      ;;
    'email')
      echo 5
      ;;
  esac
}

USER_CREDENTIALS=$(cat $CLI_PATH/stash/users.csv | grep $1)
INDEX=$(get_type_index $2)

echo $USER_CREDENTIALS | awk -F$';' "{print \$$INDEX}"
