#!/usr/bin/env bash

type_position() {
  case ${1/--/} in
    'name')
      echo '{print $1}'
      ;;
    'github')
      echo '{print $2}'
      ;;
    'slack')
      echo '{print $3}'
      ;;
    'trello')
      echo '{print $4}'
      ;;
    'email')
      echo '{print $5}'
      ;;
  esac
}

USER_CREDENTIALS=$(cat $CLI_PATH/stash/users.csv | grep $1)
TYPE=$(type_position $2)

echo $USER_CREDENTIALS | awk -F$';' "$TYPE"
