#!/usr/bin/env bash

cd $SICES_PATH

echo 'Replacing Symfony YML variables...'

path=app/config

# TODO: replace YML variebles name markup to their env values instead of static variables list
# Reference: https://stackoverflow.com/questions/31292722/sed-replace-with-dynamic-variable-build-from-backreference

sed "\
  s/\${CES_SICES_DATABASE_HOST}/$CES_SICES_DATABASE_HOST/g; \
  s/\${CES_SICES_DATABASE_PORT}/$CES_SICES_DATABASE_PORT/g; \
  s/\${CES_SICES_DATABASE_NAME}/$CES_SICES_DATABASE_NAME/g; \
  s/\${CES_SICES_DATABASE_USER}/$CES_SICES_DATABASE_USER/g; \
  s/\${SICES_MAILER_TYPE}/$SICES_MAILER_TYPE/g; \
  s/\${SICES_MAILER_HOST}/$SICES_MAILER_HOST/g; \
  s/\${SICES_MAILER_USER}/$SICES_MAILER_USER/g; \
  s/\${SICES_MAILER_PASS}/$SICES_MAILER_PASS/g; \
  s/\${SICES_MAILER_KEY}/$SICES_MAILER_KEY/g" \
  < $path/parameters_sample.yml \
  > $path/parameters.yml

if [ $CES_SICES_DATABASE_PASS ]; then
  sed -i "s/\${CES_SICES_DATABASE_PASS}/$CES_SICES_DATABASE_PASS/g;" $path/parameters.yml
fi
