<?php

namespace AppBundle\Form;


use FOS\OAuthServerBundle\Model\ClientInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use FOS\OAuthServerBundle\Model\Client;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;


class ClientType extends AbstractType
{


    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //  parent::buildForm($builder, $options); // TODO: Change the autogenerated stub


        //   $client = new Client();
        $builder
            ->add('randomId', TextType::class)
            ->add('secret', TextType::class)
            ->add('redirectUris', ChoiceType::class, array(
                'multiple' => true,
                'choices' => array(
                    'Maybe' => null,
                    'Yes' => true,
                    'No' => false,
                ),
            ));

        //   ->add('save', SubmitType::class, array('label' => 'Create Post'))
        //   ->getForm();


    }


    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'ApiBundle\Entity\Client'
        ));
    }



}
