#!/usr/bin/env bash

export PROJECT_ROOT=$SICES_PATH/backend
export CLI_PATH=$SICES_PATH/devops/cli
export PATH="$SICES_PATH/devops/cli:$PATH"

export SICES_DEVELOPMENT_PORT=8000
export SICES_DEVELOPMENT_HOST='http://localhost'
export SICES_HOMOLOG_PORT=80
export SICES_HOMOLOG_HOST=54.233.150.10
export SICES_HOMOLOG_DATABASE_NAME=sices_solar
export SICES_HOMOLOG_DATABASE_USER=mysqldevtest
export SICES_HOMOLOG_DATABASE_HOST=mysql-dev-test.crtwvzhue9fu.sa-east-1.rds.amazonaws.com
export SICES_HOMOLOG_DATABASE_PORT=3306
export SICES_HOMOLOG_DATABASE_PASS=zvQdYaPB79muWbnpct
export SICES_PRODUCTION_PORT=80
export SICES_PRODUCTION_HOST='https://app.plataformasicessolar.com.br'

export BUNDLE_DEVELOPMENT_PORT=2020
export BUNDLE_DEVELOPMENT_HOST='http://localhost'
export BUNDLE_HOMOLOG_PORT=3000
export BUNDLE_HOMOLOG_HOST=54.233.150.10
export BUNDLE_PRODUCTION_PORT=3000
export BUNDLE_PRODUCTION_HOST='https://app.plataformasicessolar.com.br'

export ISQUIK_HOMOLOG_SERVER_PORT=443
export ISQUIK_HOMOLOG_SERVER_HOST='https://api.isquik.com'
export ISQUIK_HOMOLOG_AUTH_KEY='12eb45ec-b98f-4942-9124-b7b6b389088e'
export ISQUIK_HOMOLOG_AUTH_USER='isquik-dev'
export ISQUIK_PRODUCTION_SERVER_PORT=443
export ISQUIK_PRODUCTION_SERVER_HOST='https://api.isquik.com'
export ISQUIK_PRODUCTION_AUTH_KEY='3bbafb12-5702-41a6-a4bc-813cebfba500'
export ISQUIK_PRODUCTION_AUTH_USER='sices'

export SLACK_HOOK=https://hooks.slack.com/services/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
