#!/usr/bin/env bash

export PROJECT_ROOT=$SICES_PATH/backend
export CLI_PATH=$SICES_PATH/devops/cli
export PATH="$SICES_PATH/devops/cli:$PATH"

export SICES_MAILER_TYPE=smtp
export SICES_MAILER_HOST='smtp.mail.eu-west-1.awsapps.com'
export SICES_MAILER_KEY='b7552e60db4c89c9a846954a9f2b91cb0723a267'
export SICES_MAILER_USER='naoresponder@plataformasicessolar.com.br'
export SICES_MAILER_PASS='Ze6}Kr6bWVky@z@Qsi'

export ISQUIK_HOMOLOG_SERVER_PORT=443
export ISQUIK_HOMOLOG_SERVER_HOST='https://api.isquik.com'
export ISQUIK_HOMOLOG_AUTH_KEY='12eb45ec-b98f-4942-9124-b7b6b389088e'
export ISQUIK_HOMOLOG_AUTH_USER='isquik-dev'
export ISQUIK_PRODUCTION_SERVER_PORT=443
export ISQUIK_PRODUCTION_SERVER_HOST='https://api.isquik.com'
export ISQUIK_PRODUCTION_AUTH_KEY='3bbafb12-5702-41a6-a4bc-813cebfba500'
export ISQUIK_PRODUCTION_AUTH_USER='sices'

slack_uri='https://hooks.slack.com/services/T637J8WTD'
export SLACK_HOOK_DEVOPS="$slack_uri/B6GU2PZFY/q4Va8VlWX7lv7zUv3uQIgryM"
export SLACK_HOOK_BACKLOG_API="$slack_uri/B6UGPPXFS/gCKN7pVkpvgHER7m8zSJjuZQ"
