#!/usr/bin/env bash

export PROJECT_ROOT=$SICES_PATH/backend
export CLI_PATH=$SICES_PATH/devops/cli
export PATH="$SICES_PATH/devops/cli:$PATH"

export SICES_MAILER_TYPE=smtp
export SICES_MAILER_HOST='smtp.mail.eu-west-1.awsapps.com'
export SICES_MAILER_KEY='b7552e60db4c89c9a846954a9f2b91cb0723a267'
export SICES_MAILER_USER='naoresponder@plataformasicessolar.com.br'
export SICES_MAILER_PASS='Ze6}Kr6bWVky@z@Qsi'
export SICES_AUTH_USER='1_2b14bvyiqfr4wksgcc0ck004w8og4wkwc4o4gksk4ks8oooo8g'
export SICES_AUTH_KEY='53xlex74i4kk8ckww08goc8oocw048s0wwcok84040w0kcw0ks'

export SICES_HOOK_PORT=3000

slack_uri='https://hooks.slack.com/services/T637J8WTD'
export SLACK_HOOK_TESTER="${slack_uri}/B7RG9C6QY/83hdQY97qEOsPjYWexEfobCN"
export SLACK_HOOK_DEVOPS="${slack_uri}/B6GU2PZFY/q4Va8VlWX7lv7zUv3uQIgryM"
export SLACK_HOOK_HOMOLOG="${slack_uri}/B7PPVC42D/FIXd946YfYB6wN5XBIE9P5yR"
export SLACK_HOOK_PRODUCTION="${slack_uri}/B7PKYSBEC/R2k2c5GqdzjtazDFuabywnmG"
export SLACK_HOOK_TASKS="${slack_uri}/B84MS6VNW/t2T7U7t6y1LKVRZHvOZCxPY0"
export GITHUB_REPOSITORY='https://api.github.com/repos/sices/sices'
