#!/usr/bin/env bash

export SICES_HOMOLOG_PORT=80
export SICES_HOMOLOG_IP=54.233.150.10
export SICES_HOMOLOG_HOST="http://$SICES_HOMOLOG_IP"
export SICES_HOMOLOG_URI='http://homolog.plataformasicessolar.com.br'
export SICES_HOMOLOG_DATABASE_NAME=sices_solar
export SICES_HOMOLOG_DATABASE_USER=mysqldevtest
export SICES_HOMOLOG_DATABASE_HOST='mysql-dev-test.crtwvzhue9fu.sa-east-1.rds.amazonaws.com'
export SICES_HOMOLOG_DATABASE_PORT=3306
export SICES_HOMOLOG_DATABASE_PASS='zvQdYaPB79muWbnpct'
export SICES_HOMOLOG_FTP_HOST=kolinalabs.com
export SICES_HOMOLOG_FTP_PORT=21
export SICES_HOMOLOG_FTP_USER=sicesbrasil@kolinalabs.com
export SICES_HOMOLOG_FTP_PASS='xVa0JZM}P4nf'
