services:
    # Managers

    cart_pool_manager:
        class: Ecommerce\CartPool\Manager\CartPoolManager
        arguments: ['Ecommerce\CartPool\Entity\CartPool', '@doctrine']

    # Services

    getnet_service:
        class: Ecommerce\CartPool\Service\GetnetService
        arguments: ['@cart_pool_manager', '@order_transformer']

    integrador.cart_pool_helper:
        class: Ecommerce\CartPool\Service\Integrador\CartPoolHelper
        arguments: ['@cart_has_kit_manager', '@cart_pool_manager', '@cart_manager']

    integrador.cart_pool_service:
        class: Ecommerce\CartPool\Service\Integrador\CartPoolService
        arguments: ['@cart_pool_manager', '@integrador.cart_pool_helper', '@knp_paginator']
