#!/usr/bin/env bash

USER=$($CLI_PATH/util/github-credentials --user)
NICK=$($CLI_PATH/util/user-credentials $USER --slack)
LOGIN=$($CLI_PATH/util/github-credentials --login)

if [[ -z $1 ]]; then
  BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
  ISSUE=${BRANCH/issue-/}
else
  BRANCH="issue-${1}"
  ISSUE=$1
fi

get_issue_description() {
  echo $(curl -s -X GET -u $LOGIN $GITHUB_REPOSITORY/issues/$ISSUE |
    grep -oP '(?<="body": ").*(?=",)')
}

get_block_observation() {
  local default='Issue bloqueada temporariamente para execução de issue de maior prioridade.'
  read -rep $'In portuguese, with few words, describe why this issue must be blocked and then press ENTER (Blank for default value).\n' observation > /dev/tty
  echo $([[ -z $observation ]] && echo $default || echo $observation)
}

observation="[$(date +'%d/%m/%y-%H:%M')] BLOCKED: $(get_block_observation)"
body="$(get_issue_description)\n\n${observation}"

json="{\"body\":\"${body}\"}"

curl -s -X PATCH -u $LOGIN -d "$json" $GITHUB_REPOSITORY/issues/$ISSUE > /dev/null

$CLI_PATH/ces-issue-move $ISSUE --blocked
$CLI_PATH/ces-slack-notify --devops "[$BRANCH] has been blocked by _${NICK}_"
