#!/usr/bin/env bash

cd $SICES_PATH

if [[ -z $1 ]] || [ $1 = '--help' ] || [ $1 = '-h' ]; then
  printf "ces-app-clone - help:

  Usage:

  ces-app-clone --AMBIENCE

  Exemple:

  ces-app-clone --production

  "
  exit 0;
fi

echo "Starting Deploy..."

if [ $1 = '--homolog' ] || [ $1 = '--staging' ]; then

  ambience=${CES_AMBIENCE^}
  $CLI_PATH/ces-slack-notify --devops "Starting $ambience Deploy..."
  $CLI_PATH/ces-app-clone $1
  $CLI_PATH/ces-permission-fix $1
  source $CLI_PATH/config/variables-ci $1
  $CLI_PATH/ces-app-install
  $CLI_PATH/ces-database-update
  $CLI_PATH/ces-cache-clear
  $CLI_PATH/ces-frontend-compile
  $CLI_PATH/ces-slack-notify --devops "$ambience Deploy Done!"

elif [ $1 = '--production' ]; then

  $CLI_PATH/ces-slack-notify --devops '@here: Starting Production Deploy...'
  $CLI_PATH/ces-app-clone --production
  source $CLI_PATH/config/variables-ci --production
  $CLI_PATH/ces-cache-clear
  $CLI_PATH/ces-database-update
  $CLI_PATH/ces-slack-notify --devops '@here: Production Deploy Done!'

fi

bundles/isquik/node_modules/.bin/pm2 restart 0

echo 'Done.'
