#!/usr/bin/env bash

if [[ -z $1 || $1 = '--installation-list' ]]; then
  printf 'Dependencies - installation commands

  Requirements:

    * Apache2
    * PHP
      * php-mbstring
      * php-xml
      * php-mysql
      * php-intl
      * php-common
      * php-curl
      * php-sqlite
      * php-gd
      * php-zip
    * Nodejs
    * Curl
    * Yarn
    * Composer
    * Mysql-server

  How to:

    Apache:

      $ sudo apt-get install apache2

    PHP:

      $ sudo apt-get install php

    pacotes do PHP:

      $ sudo apt install php7.0-mbstring php7.0-xml php7.0-mysql php7.0-intl php7.0-common php7.0-curl php7.0-sqlite php7.0-gd php7.0-zip

    Nodejs:

      $ sudo apt-get install nodejs

    Curl:

      $ sudo apt install curl

    Yarn (apenas ambiente desenvolvimento):

      $ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      $ echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      $ sudo apt-get update
      $ sudo apt-get install yarn

    Composer:

      $ sudo apt install composer

    Mysql Server:

      $ echo "deb http://repo.mysql.com/apt/ubuntu/ precise mysql-apt-config deb http://repo.mysql.com/apt/ubuntu/ precise mysql-5.6" | sudo tee /etc/apt/sources.list.d/mysql.list
      $ curl -s http://ronaldbradford.com/mysql/mysql.gpg | sudo apt-key add -
      $ sudo apt-get update
      $ sudo apt-get install mysql-server-5.6 \n\n'

  exit 0

elif [[ $1 = '--full' ]]; then
  echo "Installing Sices dependencies..."

  sudo apt install curl
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  sudo apt-get update
  sudo apt-get install\
    apache2\
    php\
      php7.0-mbstring\
      php7.0-xml\
      php7.0-mysql\
      php7.0-intl\
      php7.0-common\
      php7.0-curl\
      php7.0-sqlite\
      php7.0-gd\
      php7.0-zip\
    nodejs\
    yarn\
    composer\
    git\
  -y

  echo "deb http://repo.mysql.com/apt/ubuntu/ precise mysql-apt-config deb http://repo.mysql.com/apt/ubuntu/ precise mysql-5.6"\
    | sudo tee /etc/apt/sources.list.d/mysql.list
  curl -s http://ronaldbradford.com/mysql/mysql.gpg | sudo apt-key add -
  sudo apt-get update
  sudo apt-get install mysql-server-5.6
fi
