#!/usr/bin/env bash

cd $SICES_PATH

printf "
Cloning homolog database...
Note: This process can be a little slow!
"

$CLI_PATH/ces-permission-fix --development
source $CLI_PATH/config/homolog/variables

if [ -z ${1+x} ]; then
  echo "Enter your mysql password:"
  read -s password
else
  password=$1
fi

mkdir .mirror

$CLI_PATH/ces-database-clone
$CLI_PATH/ces-database-import $password

rm -rf .mirror

$CLI_PATH/ces-cache-clear
$CLI_PATH/ces-database-update

$CLI_PATH/util/user-notify 'Database mirror done.'
echo 'Database mirror done.'
