#!/usr/bin/env bash

cd $SICES_PATH

echo "Starting $1 Application..."

source $CLI_PATH/config/variables-ci $1
bash $CLI_PATH/ces-app-install

bundle_path=bundles/isquik

if [ -z ${1+x} ] || [ $1 == '--development' ]; then

  bash $CLI_PATH/ces-database-update
  echo "Sices app starting on $CES_SICES_HOST:$CES_SICES_PORT"
  php app/console server:run &

  echo "Isquik bundle starting on $CES_BUNDLE_HOST:$CES_BUNDLE_PORT"
  $bundle_path/node_modules/.bin/node-supervisor --harmony $bundle_path/index.js &

  # Enable job control
  set -m

  while :
  do
    read input
    [[ $input == finish ]] && break

    # Run the command in background
    bash -c "$input" &

    # Move the command back-into foreground
    fg %- > /dev/null 2>&1;
  done
fi

if [[ $1 == '--homolog' ]] || [[ $1 == '--production' ]]; then

  echo "Isquik bundle starting on $CES_BUNDLE_HOST:$CES_BUNDLE_PORT"
  $bundle_path/node_modules/.bin/pm2 start $bundle_path/index.js --node-args="--harmony" -n "bundle"

fi
