#!/usr/bin/env bash

# colors pallet
CT='\033[0;33m'
CI='\033[0;32m'
CE='\033[0;31m'
CD='\033[0;00m'
CM='\033[0;30m'

LOGIN=$($CLI_PATH/util/github-credentials --login)

# contains labels formatted by: prefix:value
LABELS=$(curl -s -X GET -u $LOGIN $GITHUB_REPOSITORY/labels \
  | grep name \
  | grep -v Stage \
  | sed 's/"//g;s/,//g' \
  | awk '{print $2 $3}'
)

# contains milestones formatted by: id:prefix:value
MILESTONES=$(curl -s -X GET -u $LOGIN $GITHUB_REPOSITORY/milestones \
  | grep -E 'number|title' \
  | tr -d '[:space:]' \
  | sed 's/"//g;s/,//g;s/number:/\n/g;s/title//g;' \
  | sed '1{/^$/d};$a\\r'
)

# contains Stage prefix name
STAGE_PREFIX=Stage

# contains prefixes names without repetition
GENERAL_PREFIXES=$(printf "${LABELS}" \
  | awk -F$':' '{print $1}' \
  | awk '!a[$0]++'
)

# contains selection titles
declare -A HEADERS=(
  [Category]='Select at least one category:\nUsage: enter 0 for multiple choose'
  [Milestone]='Select the milestone:'
  [Priority]='Select the priority:'
  [Stage]='Select the stage:'
  [Type]='Select the type:'
)

# contains the selected milestone
ISSUE_MILESTONE=''

# contains all the selected labels
ISSUE_LABELS=()

# increments ISSUE_LABELS with the selected label prefixing it
set_issue_label()
{
  echo -e "${CI}> Selected label: ${2}${CM}"
  ISSUE_LABELS=(${ISSUE_LABELS[@]} "${1}:${2}")
}

# returns all labels filtered by prefix
get_prefixed_labels()
{
  printf "${LABELS}" | grep $1 | awk -F$':' '{print $2}'
}

# returns allowed stage labels, based on Category chosen
get_stage_labels()
{
  local backlog_type='general'

  for label in ${ISSUE_LABELS[@]}; do
    [[ $label == *'Devops'* ]] && backlog_type='devops'
  done

  echo "Backlog-${backlog_type}"
  echo 'To-do'
}

# request the user to select multiple labels in the category options list
set_issue_multiple_labels()
{
  local prefix=$1
  local options=$2
  local options_length=$(printf "${options}" | awk 'END {print NR}')

  local error_message='Error: You must enter just valid numbers'
  local usage_message='Usage: separate number using comma. sample: 1,4'
  local label=''

  printf "${CT}${usage_message}${CM}\n#? "
  read chosen

  # chosen validation, must be integer numbers and be allowed index
  for label_index in ${chosen//,/ }; do
    re='^[0-9]+$'
    [[ ! $label_index =~ $re || $label_index -gt $options_length ]] && {
      echo -e "${CE}${error_message}${CM}"
      set_issue_multiple_labels $prefix "$options"
      return 1
    }
  done

  # if validations is OK, calls set_issue_label
  for label_index in ${chosen//,/ }; do
    label=$(echo $options | awk "{print \$$label_index}")
    set_issue_label $prefix $label
  done
}

# requests the user to select a label in the options list
select_label()
{
  local prefix=$1
  local options=$2
  local error_message='Error: you must choose a valid option'

  echo -e "${CT}${HEADERS[$prefix]}${CM}"

  select label in $options; do
    if [[ -n $label ]]; then
      set_issue_label $prefix $label
      break
    elif [[ $prefix == 'Category' ]]; then
      set_issue_multiple_labels $prefix "${options}"
      break
    else
      echo -e "${CE}${error_message}${CM}"
    fi
  done

  printf "${CD}"
}

select_milestone()
{
  echo -e "${CT}${HEADERS[Milestone]}${CM}"

  select milestone in $(printf "$MILESTONES" | awk -F$':' '{print $3}'); do
    ISSUE_MILESTONE=$(printf "$MILESTONES" | grep $milestone)
    break
  done
}

for prefix in ${GENERAL_PREFIXES[@]}; do
  select_label $prefix "$(get_prefixed_labels $prefix)"
done
select_label $STAGE_PREFIX "$(get_stage_labels)"

select_milestone

echo ${ISSUE_LABELS[@]}
echo $ISSUE_MILESTONE
