#!/usr/bin/env bash

cd $SICES_PATH

if [[ -z $1 ]] || [ $1 = '--help' ] || [ $1 = '-h' ]; then
  printf "ces-new-task - help:
  Usage:
  ces-new-task [ISSUE_NUMBER]

  Exemple:
  ces-new-task 100
  "
  exit 0;
fi

git checkout master
git fetch origin
git pull origin master
git checkout -b issue-$1

$CLI_PATH/ces-app-install
$CLI_PATH/ces-database-update

echo "Done, now on Branch: $1"
