#!/usr/bin/env bash

cd $SICES_PATH

echo "Installing packages dependencies..."

cd backend
  composer install
  npm install
  bash $CLI_PATH/util/bug-fix
cd ../

cd bundles/isquik
  npm install
cd ../../
