#!/usr/bin/env bash

cd $SICES_PATH

echo 'Fixing KNP Bugs...'

path=vendor/knplabs/knp-components/src/Knp/Component/Pager/Event/Subscriber/Filtration/Doctrine/ORM/Query

initial='$alias = reset($parts);'
final='$alias = trim(reset($parts));'

sed "s/$initial/$final/g" <$path/WhereWalker.php >$path/TempFixed.php
mv $path/TempFixed.php $path/WhereWalker.php
