#!/usr/bin/env bash

cd $SICES_PATH

if [[ -z $1 ]] || [ $1 = '--help' ] || [ $1 = '-h' ]; then
  printf "ces-issue-start - help:
  Usage:
  ces-issue-start [ISSUE_NUMBER] \n
  Exemple:
  ces-issue-start 100 \n"
  exit 0;
fi

USER=$($CLI_PATH/util/github-credentials --user)
LAST_BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

git checkout master
git fetch origin
git pull origin master
git checkout -b issue-$1

$CLI_PATH/ces-app-install
$CLI_PATH/ces-database-update
$CLI_PATH/ces-log-clear

$CLI_PATH/ces-issue-assign $1
$CLI_PATH/ces-issue-move $1 --in-progress

if [ $LAST_BRANCH != 'master' ]; then
  read -p "Do you wanna $LAST_BRANCH to be tested by product team? [Y/n]: " accept > /dev/tty

  if [[ $accept == 'y' ]]; then
    $CLI_PATH/ces-issue-request --testing
  else
    $CLI_PATH/ces-issue-close "${LAST_BRANCH/issue-/}"
  fi
fi

$CLI_PATH/ces-slack-notify --devops "[issue-$1] _${USER}_ has been working on"
$CLI_PATH/util/user-notify 'Branch created' "now on issue-$1"
echo "Everything done, now on Branch: issue-$1"
