#!/usr/bin/env bash

cd $SICES_PATH

echo "Installing packages dependencies..."

if [ $CES_AMBIENCE = 'development' ]; then
  node_install='yarn install'
else
  node_install='npm install'
fi

cd backend
  composer install
  $node_install
  $CLI_PATH/util/bug-fix
cd ../

cd devops/hook
  $node_install
cd ../../
