#!/usr/bin/env bash

cd $SICES_PATH

echo "Starting App configurations..."

$CLI_PATH/util/variables-replacer

if [ -z ${1+x} ] || [ $1 = '--development' ]; then

  cp $CLI_PATH/util/pre-push .git/hooks/pre-push
  $CLI_PATH/ces-database-config --development

else

  mkdir .temp
  mkdir .mirror
  mkdir .backup
  mkdir .uploads
  mkdir .uploads/order
  mkdir .uploads/proposal
  mkdir .uploads/component
  mkdir .uploads/order/proforma
  mkdir .uploads/order/payment
  mkdir .uploads/proposal/proposal
  mkdir .uploads/component/image
  mkdir .uploads/component/datasheet

fi
