#!/usr/bin/env bash

echo "Sending Slack devops chat notification..."

if [ $1 = '--backlog-api' ]; then
  slack_hook=$SLACK_HOOK_BACKLOG_API
elif [ $1 = '--devops' ]; then
  slack_hook=$SLACK_HOOK_DEVOPS
else
  echo "Invalid chat argument"
  exit 1
fi

message=$(echo ${2:0:1500} | sed 's/"/\\"/g')

curl -s \
  -X POST \
  -H "Content-type:application/json" \
  -d "{\"attachments\": [{\"fallback\": \"ReferenceError - UI is not defined: https://honeybadger.io/path/to/event/\",\"text\": \"<https://honeybadger.io/path/to/event/|ReferenceError> - UI is not defined\",\"fields\": [{\"title\": \"Project\",\"value\": \"Awesome Project\",\"short\": true},{\"title\": \"Environment\",\"value\": \"$CES_AMBIENCE\",\"short\": true}],\"color\": \"#F35A00\"},{\"text\": \"$message\", \"link_names\": \"1\"}]}" \
  $slack_hook
