#!/usr/bin/env bash

cd $SICES_PATH

path=/var/www/

echo "Creating current version Backup..."
rsync -avzh $path/** $path/.backup

echo "Importing Temp files from homolog..."
rsync -azvv -e "ssh -i $SICES_PATH/devops/aws/homolog.pem" admin@54.233.150.10:$path/** $path/.temp

echo "Deploying files from Temp..."
rsync -avzh --delete $path/.temp/** $path
