#!/usr/bin/env bash

cd $SICES_PATH

if [[ -z $1 ]] || [ $1 = '--help' ] || [ $1 = '-h' ]; then
  printf "ces-app-clone - help:

  Usage:

  ces-app-clone --AMBIENCE

  Exemple:

  ces-app-clone --production

  "
  exit 0;
fi

echo "Cloning $1 files..."

if [ $1 = '--homolog' ] || [ $1 = '--staging' ]; then

  git fetch origin
  GIT_WORK_TREE=$SICES_PATH git checkout -f
  git pull origin master -f

elif [ $1 = '--production' ]; then

  if [ -z ${2+x} ] || [ $2 = '--homolog' ]; then

    source $CLI_PATH/config/homolog/variables
    host=$SICES_HOMOLOG_IP
    origin='homolog'

  else
    "Invalid origin server argument"
    exit 1
  fi

  echo "Importing Temp files from $origin Server..."
  rsync -azvv --delete -e \
    "ssh -i $SICES_PATH/devops/aws/$origin.pem" admin@$host:$SICES_PATH/** $SICES_PATH/.temp

  echo "Creating current version Backup..."
  rsync -avzh --delete $SICES_PATH/** $SICES_PATH/.backup

  echo "Moving untracked files..."
  rsync -avzh $SICES_PATH/.backup/backend/web/uploads/** $SICES_PATH/.temp/backend/web/uploads
  rsync -avzh $SICES_PATH/.backup/backend/storage/** $SICES_PATH/.temp/backend/storage

  # Remove it after deploy command optimizations
  rm $SICES_PATH/.temp/devops/aws/homolog.pem
  rm $SICES_PATH/.temp/devops/aws/staging.pem
  rm $SICES_PATH/.temp/backend/app/config/parameters.yml
  rm $SICES_PATH/.temp/backend/src/AppBundle/Service/Notifier/Notifier.php
  cp \
    $SICES_PATH/.backup/devops/aws/homolog.pem \
    $SICES_PATH/.temp/devops/aws/homolog.pem
  cp \
    $SICES_PATH/.backup/devops/aws/staging.pem \
    $SICES_PATH/.temp/devops/aws/staging.pem
  cp \
    $SICES_PATH/.backup/backend/app/config/parameters.yml \
    $SICES_PATH/.temp/backend/app/config/parameters.yml
  cp \
    $SICES_PATH/.backup/backend/src/AppBundle/Service/Notifier/Notifier.php \
    $SICES_PATH/.temp/backend/src/AppBundle/Service/Notifier/Notifier.php
  # Finish Remove it

  echo "Deploying files from Temp..."
  rsync -avzh --delete $SICES_PATH/.temp/** $SICES_PATH

fi
