#!/usr/bin/env bash

cd $SICES_PATH

echo 'Fixing permissions...'

if [ -z ${1+x} ] || [ $1 == '--development' ]; then

  chmod 600 devops/aws/homolog.pem
  chmod 600 devops/aws/staging.pem

elif [ $1 == '--homolog' ] || [ $1 == '--staging' ]; then

  sudo chown -R www-data:admin /var/www/*
  sudo chmod -R g+rwx /var/www/*

  sudo chmod 775 backend/web/uploads
  sudo chmod 775 backend/web/uploads/components
  sudo chmod 775 .uploads/proposal

fi
