#!/usr/bin/env bash

cd $SICES_PATH

echo 'Extracting compressed file and importing Database...'

db_sql="sices-homolog.sql"
db_tar="sices-homolog.tar.gz"
local_path=.mirror

tar -xzvf $local_path/$db_tar $local_path

mysql -u root -p$1 sices_solar < $local_path/$db_sql 2>/dev/null &
./$CLI_PATH/util/progress-spinner $!
