#!/usr/bin/env bash

cd $SICES_PATH

echo 'Compiling frontend...'

cd backend
  rm -rf web/public

  mkdir web/public
  mkdir web/public/assets

  cp -r web/assets/images web/public/assets/images
  cp -r web/assets/font-awesome web/public/assets/font-awesome

  php app/console assetic:dump

  rm -rf web/app
cd ../

cd frontend
  node --max-old-space-size=512 .webpack.prod.conf.js
cd ../

if [[ $CES_AMBIENCE = 'development' ]]; then
  $CLI_PATH/util/user-notify 'Frontend compile' 'done!'
fi
