#!/usr/bin/env bash

echo "Sending Slack devops chat notification..."

message=$(echo ${2:0:1500} | sed 's/"/\\"/g')

if [ $1 = '--devops' ]; then

  slack_hook=$SLACK_HOOK_DEVOPS
  json="{\"text\": \"$message\", \"link_names\": \"1\"}"

else

  echo "Invalid chat argument"
  exit 1

fi

curl -s \
  -X POST \
  -H "Content-type:application/json" \
  -d "$json" \
  $slack_hook
