#!/usr/bin/env bash

if [[ -z $1 ]] || [ $1 = '--help' ] || [ $1 = '-h' ]; then
  printf "ces-issue-assign - help:
  Usage:
  ces-issue-assign [ISSUE_NUMBER] \n
  Exemple:
  ces-issue-assign 100 \n"
  exit 0;
fi

ISSUE=$1
USER=$CLI_PATH/util/github-credentials --user
LOGIN=$CLI_PATH/util/github-credentials --login

ASSIGNEES="{\"assignees\": [\"$USER\"]}"

curl -X POST -u $LOGIN -d $ASSIGNEES $GITHUB_REPOSITORY/issues/$ISSUE/assignees > /dev/null 2>&1
