#!/usr/bin/env bash

cd $SICES_PATH

echo "Starting Application..."

isquik=bundles/isquik

if [ -z ${1+x} ] || [ $1 = '--development' ]; then

  $CLI_PATH/ces-app-install
  $CLI_PATH/ces-database-update

  echo "Sices app starting on $CES_SICES_HOST:$CES_SICES_PORT"
  php backend/app/console server:run &

  echo "Isquik bundle starting on $CES_BUNDLE_HOST:$CES_BUNDLE_PORT"
  $isquik/node_modules/.bin/node-supervisor --harmony $isquik/index.js &

  $CLI_PATH/util/user-notify 'Sices App and Bundle Isquik have been started.'

  # Enable job control
  set -m

  while :
  do
    read input
    [[ $input == finish ]] && break

    # Run the command in background
    bash -c "$input" &

    # Move the command back-into foreground
    fg %- > /dev/null 2>&1;
  done

elif [[ $1 == '--homolog' ]] || [[ $1 == '--production' ]]; then

  echo "Isquik bundle starting on $CES_BUNDLE_HOST:$CES_BUNDLE_PORT"
  $isquik/node_modules/.bin/pm2 start $isquik/index.js --node-args="--harmony" -n "bundle"

fi
