#!/usr/bin/env bash

cd $SICES_PATH

echo 'Fixing permissions...'

if [ -z ${1+x} ] || [ $1 == '--development' ]; then

  chmod 600 devops/aws/homolog.pem

elif [ $1 == '--homolog' ]; then

  sudo chown -R www-data:admin /var/www/*
  sudo chmod -R g+rwx /var/www/*

fi;
