#!/usr/bin/env bash

if [[ $1 = '--list' ]]; then
  printf '
  Dependencies List:
  1. Instalando o Apache
  ----------------------

  ```
  $ sudo apt-get install apache2
  ```


  2. Instalando o PHP
  ----------------------

  ```
  $ sudo apt-get install php
  ```


  3. Instalando os pacotes do PHP

  ```
  $ sudo apt install php-mbstring php-xml php-mysql php-intl php-common php-curl
  ```


  4. Instalando o Nodejs
  ----------------------

  ```
  $ sudo apt-get install nodejs
  ```


  5. Instalando o Yarn
  --------------------

  ```
  $ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  $ echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  $ sudo apt-get update
  $ sudo apt-get install yarn
  ```


  6. Instalando o Composer
  ------------------------

  ```
  $ sudo apt install composer
  ```


  7. Instalando o Git
  -------------------

  ```
  $ sudo apt install git
  ```

  8. Instalando o mysql-server
  ----------------------------

  ```
  $ sudo apt install mysql-server
  ```
  '
  exit 0
fi

echo "Installing Sices dependencies..."

sudo apt install curl
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get update
sudo apt-get install apache2 php php-mbstring php-xml php-mysql php-intl php-common php-curl mysql-server nodejs nodejs-legacy yarn composer git -y
