#!/usr/bin/env bash

end=$((SECONDS+3600))
time=$(date +'%H:%M:%S')

echo 'Hardware:  CPU  MEM  Connections'

while [ $SECONDS -lt $end ]; do
  network_conections=$(netstat -natu | grep 'ESTABLISHED' | wc -l)
  cpu_processes=($(ps aux --sort -rss | grep -v USER | awk '{print $3}'))
  memory_processes=($(ps aux --sort -rss | grep -v USER | awk '{print $4}'))

  cpu_total=0
  memory_total=0

  for memory_process in "${memory_processes[@]}"; do
    memory_value=$(sed 's/\.//g;s/0//g' <<< $memory_process)

    [[ -n $memory_value ]] && {
      memory_total=$[$memory_total+$memory_value]
    }
  done

  for cpu_process in "${cpu_processes[@]}"; do
    cpu_value=$(sed 's/\.//g;s/0//g' <<< $cpu_process)

    [[ -n $cpu_value ]] && {
      cpu_total=$[$cpu_total+$cpu_value]
    }
  done

  echo "[${time}] $[$cpu_total/10]% $[$memory_total/10]% ${network_conections}"
  sleep 5
done
