#!/usr/bin/env bash

cd $SICES_PATH

if [[ -z $1 ]] || [ $1 = '--help' ] || [ $1 = '-h' ]; then
  printf "ces-new-task - help:
  Usage:
  ces-new-task [ISSUE_NUMBER] [GITHUB_USER_NAME]

  Exemple:
  ces-new-task 100 rafaelkendrik
  "
  exit 0;
fi

git checkout master
git fetch origin
git pull origin master
git checkout -b issue-$1

$CLI_PATH/ces-app-install
$CLI_PATH/ces-database-update

if [ $2 ]; then
  user=$(head -n1 ~/.ces-credentials | tr -d "[:space:]")
  pass=$(head -n2 ~/.ces-credentials | tail -1 | tr -d "[:space:]")
  u="$user:$pass"

  curl -X POST -u $u -d "{\"assignees\": [\"$user\"]}" $GITHUB_REPOSITORY/issues/$1/assignees
  curl -X DELETE -u $u $GITHUB_REPOSITORY/issues/$1/labels/Stage:%20To-do
  curl -X POST -u $u -d '["Stage: In-progress"]' $GITHUB_REPOSITORY/issues/$1/labels
fi

$CLI_PATH/util/user-notify "Branch created" "now on issue-$1"
echo "Done, now on Branch: issue-$1"
