#!/usr/bin/env bash

cd $SICES_PATH

_getHelp()
{
  printf "ces-app-clone - help:
  Usage:
  ces-app-clone --AMBIENCE \n
  Exemple:
  ces-app-clone --production \n
  Avaliable Args:
  [ --homolog ]
  [ --staging ]
  [ --production
      --homolog | --staging] \n"
}

if [[ -z $1 ]] || [ $1 = '--help' ] || [ $1 = '-h' ]; then
  _getHelp
  exit 0
fi

echo "Cloning $1 files..."

if [ $1 = '--homolog' ] || [ $1 = '--staging' ]; then

  git fetch origin
  GIT_WORK_TREE=$SICES_PATH git checkout -f
  git pull origin master -f

elif [ $1 = '--production' ]; then

  if [ -z ${2+x} ] || [ $2 = '--homolog' ]; then

    source $CLI_PATH/config/homolog/variables
    host=$SICES_HOMOLOG_IP
    origin='homolog'

  else
    echo "Invalid Origin Argument"
    _getHelp
    exit 1
  fi

  echo "Importing Temp files from $origin Server..."
  rsync -azvv --delete -e \
    "ssh -i $SICES_PATH/devops/aws/$origin.pem" admin@$host:$SICES_PATH/** $SICES_PATH/.temp

  echo "Creating current version Backup..."
  rsync -avzh --delete $SICES_PATH/** $SICES_PATH/.backup

  echo "Deploying files from Temp..."
  rsync -avzh --delete $SICES_PATH/.temp/** $SICES_PATH

else
  echo "Invalid Ambience Argument"
  _getHelp
  exit 1
fi
