#!/usr/bin/env bash

cd $SICES_PATH

echo "Installing packages dependencies..."

cd backend
  composer install
  yarn install
cd ../

cd devops/hook
  yarn install
cd ../../

cd frontend
  yarn install
cd ../

$CLI_PATH/util/bug-fix --dependencies
