#!/usr/bin/env bash

cd $SICES_PATH

if [[ -z $1 ]] || [ $1 = '--help' ] || [ $1 = '-h' ]; then
  printf "ces-app-clone - help:

  Usage:

  ces-app-clone --AMBIENCE

  Exemple:

  ces-app-clone --production

  "
  exit 0;
fi

echo "Starting Deploy..."

if [ $1 = '--homolog' ] || [ $1 = '--staging' ]; then

  $CLI_PATH/ces-slack-notify --homolog "Starting ${CES_AMBIENCE^} Deploy..."
  $CLI_PATH/ces-app-clone $1
  $CLI_PATH/ces-permission-fix $1
  source $CLI_PATH/config/variables-ci $1
  $CLI_PATH/ces-app-install
  $CLI_PATH/ces-database-update
  $CLI_PATH/ces-cache-clear
  $CLI_PATH/ces-frontend-compile
  $CLI_PATH/ces-slack-notify --homolog "${CES_AMBIENCE^} Deploy Done!"

elif [ $1 = '--production' ]; then

  $CLI_PATH/ces-slack-notify --production '@here: Starting Production Deploy...'
  $CLI_PATH/ces-permission-fix --production
  $CLI_PATH/ces-app-clone --production --homolog
  source $CLI_PATH/config/variables-ci --production
  $CLI_PATH/ces-app-config --production
  $CLI_PATH/ces-cache-clear
  $CLI_PATH/ces-database-update

  # Cleaning uploaded files
  rm .uploads/component/image/**
  rm .uploads/component/datasheet/**
  rm .uploads/proposal/proposal/**
  rm .uploads/order/payment/**
  rm .uploads/order/proforma/**
  rm .uploads/order/order/**

  $CLI_PATH/ces-slack-notify --production '@here: Production Deploy Done!'
fi

echo 'Done.'
