#!/usr/bin/env bash

LOGIN=$($CLI_PATH/util/github-credentials --login)

# contains labels formatted by: prefix:value
LABELS=$(curl -s -X GET -u $LOGIN $GITHUB_REPOSITORY/labels \
  | grep name \
  | sed 's/"//g;s/,//g' \
  | awk '{print $2 $3}'
)

# contains prefixes compacted
PREFIXES=$(printf "${LABELS}" \
  | awk -F$':' '{print $1}' \
  | awk '!a[$0]++'
)

# contains selection titles
declare -A HEADERS=(
  [Category]='Select at least one category:\nUsage: comma to pick more than one'
  [Priority]='Select the priority:'
  [Stage]='Select the stage:'
  [Type]='Select the type:'
)

# returns all labels filtered by prefix
get_prefix_labels()
{
  printf "${LABELS}" | grep $1 | awk -F$':' '{print $2}'
}

for prefix in ${PREFIXES[@]}; do
  printf "\n${HEADERS[$prefix]}\n"

  OPTIONS=$(get_prefix_labels $prefix)
  select option in $OPTIONS; do
    echo $option
    break
  done
done
