#!/usr/bin/env bash

cd $SICES_PATH

if [[ -z $1 ]] || [ $1 = '--help' ] || [ $1 = '-h' ]; then
  printf "ces-app-clone - help:

  Usage:

  ces-app-clone --AMBIENCE

  Exemple:

  ces-app-clone --production

  "
  exit 0;
fi

echo "Starting Deploy..."

if [ $1 = '--homolog' ] || [ $1 = '--staging' ]; then

  ./devops/cli/ces-slack-notify 'Starting Homolog Deploy...'

  ./devops/cli/ces-app-clone $1
  ./devops/cli/ces-permission-fix $1

  source $CLI_PATH/config/variables-ci $1
  ./devops/cli/ces-app-install

  bundles/isquik/node_modules/.bin/pm2 restart 0
  ./devops/cli/ces-database-update
  ./devops/cli/ces-cache-clear
  ./devops/cli/ces-frontend-compile

  ./devops/cli/ces-slack-notify 'Homolog Deploy Done!'

elif [ $1 = '--production' ]; then

  bash $CLI_PATH/ces-slack-notify 'Starting Production Deploy...'

  bash $CLI_PATH/ces-app-clone --production
  source $CLI_PATH/config/variables-ci --production

  bash $CLI_PATH/ces-cache-clear
  bash $CLI_PATH/ces-database-update
  bundles/isquik/node_modules/.bin/pm2 restart 0

  bash $CLI_PATH/ces-slack-notify 'Production Deploy Done!'

fi

echo 'Done.'
