#!/usr/bin/env bash

cd $SICES_PATH

echo 'Note: This process can be a little slow!'

exec $CLI_PATH/ces-permission-fix

if [ -z ${1+x} ]; then
  echo 'Cloning homolog database... enter your mysql password:'
  read -s password
else
  password=$1
fi

mkdir .mirror

exec $CLI_PATH/ces-database-clone
exec $CLI_PATH/ces-database-import $password

rm -rf .mirror

exec $CLI_PATH/ces-cache-clear
exec $CLI_PATH/ces-database-update

echo 'Database mirror done.'
