#!/usr/bin/env bash

LOGIN=$($CLI_PATH/util/github-credentials --login)

# contains labels formatted by: prefix:value
LABELS=$(curl -s -X GET -u $LOGIN $GITHUB_REPOSITORY/labels \
  | grep name \
  | grep -v Stage \
  | sed 's/"//g;s/,//g' \
  | awk '{print $2 $3}'
)

# contains Stage prefix name
STAGE_PREFIX=Stage

# contains prefixes names without repetition
GENERAL_PREFIXES=$(printf "${LABELS}" \
  | awk -F$':' '{print $1}' \
  | awk '!a[$0]++'
)

# contains selection titles
declare -A HEADERS=(
  [Category]='Select at least one category:\nUsage: comma to pick more than one'
  [Priority]='Select the priority:'
  [Stage]='Select the stage:'
  [Type]='Select the type:'
)

# returns all labels filtered by prefix
get_prefixed_labels()
{
  printf "${LABELS}" | grep $1 | awk -F$':' '{print $2}'
}

# request user to select labels options and increments ISSUE_LABELS with them
declare -A ISSUE_LABELS
select_label()
{
  local prefix=$1
  local options=$2

  printf "\n${HEADERS[$prefix]}\n"

  select option in $options; do
    echo "Selected label: ${option}"
    ISSUE_LABELS[$prefix]=$option
    break
  done
}

# returns allowed stage labels, based on Category chosen
get_stage_labels()
{
  if [[ ${ISSUE_LABELS[Category]} == 'Devops' ]]; then
    echo 'Backlog-Devops'
  else
    echo 'Backlog-General'
  fi

  echo 'To-do'
}

for prefix in ${GENERAL_PREFIXES[@]}; do
  select_label $prefix "$(get_prefixed_labels $prefix)"
done

select_label $STAGE_PREFIX "$(get_stage_labels)"

echo ${ISSUE_LABELS[@]}
