#!/usr/bin/env bash

echo "Sending Slack devops chat notification..."

message=$(echo $1 | sed 's/"/\\"/g')

curl -s \
  -X POST \
  -H "Content-type:application/json" \
  -d "{\"text\": \"@here: $message\", \"link_names\": \"1\"}" \
  $SLACK_HOOK
