#!/usr/bin/env bash

_getHelp()
{
  printf "ces-token-request - help:
  Usage:
  ces-token-request --[APPLICATION] --[AMBIENCE] \n
  Exemple:
  ces-token-request --sices --homolog \n
  Avaliable Args:
  [--sices
    --production | --homolog | --development] \n"
}

if [[ -z $1 ]] || [[ -z $2 ]] || [ $1 = '--help' ] || [ $1 = '-h' ]; then
  _getHelp
  exit 0;
fi

application=${1/--/}
ambience=${2/--/}

source $CLI_PATH/config/$ambience/variables

_getSicesHost()
{
  if [ $ambience = 'development' ]; then
    echo $SICES_DEVELOPMENT_HOST:$SICES_DEVELOPMENT_PORT
  elif [ $ambience = 'homolog' ]; then
    echo $SICES_HOMOLOG_HOST:$SICES_HOMOLOG_PORT
  elif [ $ambience = 'production' ]; then
    echo $SICES_PRODUCTION_HOST:$SICES_PRODUCTION_PORT
  fi
}

if [ $application = 'sices' ]; then

  user=$SICES_AUTH_USER
  key=$SICES_AUTH_KEY
  host=$(_getSicesHost)

  curl "$host/oauth/v2/token?client_id=$user&client_secret=$key&grant_type=client_credentials"; echo

fi
