#!/usr/bin/env bash

echo "Installing Sices dependencies..."

sudo apt install curl
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get update
sudo apt-get install apache2 php php-mbstring php-xml php-mysql php-intl php-common php-curl mysql-server nodejs nodejs-legacy yarn composer git -y
