#!/usr/bin/env bash

if [[ -z $1 ]] || [ $1 = '--help' ] || [ $1 = '-h' ]; then
  printf "ces-issue-info - help:
  Usage:
  ces-issue-info [ISSUE_NUMBER] --[INFO_TYPE] \n
  Exemple:
  ces-issue-info 100 --stage \n"
  exit 0;
fi

ISSUE=$1
LOGIN=$($CLI_PATH/util/github-credentials --login)
INFO=$(curl -s -X GET -u $LOGIN $GITHUB_REPOSITORY/issues/$ISSUE)

get_current_stage() {
  local state=$(echo $INFO | python -m json.tool | grep -oP '(?<="state": ").*(?=",)' | tail -n1)

  if [[ $state == 'closed' ]]; then
    echo 'Closed'
    exit 0
  fi

  local label=$(echo $INFO | python -m json.tool | grep -oP '(?<="Stage: ).*(?=",)')

  if [[ $label ]]; then
    echo $label
    exit 0
  fi

  echo 'Backlog-general'
}

if [[ $2 == '--stage' ]]; then
  get_current_stage
fi
