#!/usr/bin/env bash

if [[ -z $1 || $1 = '--installation-list' ]]; then
  printf 'Dependencies - installation commands

  Required:

    * Apache2
    * PHP
      * php-mbstring
      * php-xml
      * php-mysql
      * php-intl
      * php-common
      * php-curl
      * php-sqlite
      * php-gd
      * php-zip
    * Nodejs
    * Curl
    * Yarn
    * Composer
    * Mysql-server

  How to:

    Apache:

      $ sudo apt-get install apache2

    PHP:

      $ sudo apt-get install php

    pacotes do PHP:

      $ sudo apt install php-mbstring php-xml php-mysql php-intl php-common php-curl php-sqlite php-gd php-zip

    Nodejs:

      $ sudo apt-get install nodejs

    Curl:
      $ sudo apt install curl

    Yarn (apenas ambiente desenvolvimento):

      $ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      $ echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      $ sudo apt-get update
      $ sudo apt-get install yarn

    Composer:

      $ sudo apt install composer

    Mysql Server:

      $ sudo apt install mysql-server \n\n'
  exit 0

elif [[ $1 = '--full' ]]; then
  echo "Installing Sices dependencies..."

  sudo apt install curl
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  sudo apt-get update
  sudo apt-get install apache2 php php-mbstring php-xml php-mysql php-intl php-common php-curl php-sqlite php-gd php-zip mysql-server nodejs yarn composer git -y
fi
