#!/usr/bin/env bash

cd $SICES_PATH

echo 'Fixing permissions...'

if [ $1 == '--homolog' ] || [ $1 == '--staging' ]; then

  sudo chown -R www-data:admin /var/www/*
  sudo chmod -R g+rwx /var/www/*

fi

sudo chmod 600 devops/aws/*
sudo chmod -R 775 .uploads

