#!/usr/bin/env bash

cd $SICES_PATH

echo "Starting database configuration..."

if [ -z ${1+x} ] || [ $1 == '--development' ]; then

  echo "Enter your mysql password:"
  read -s password

  parameters=app/config/parameters.yml
  sample=app/config/parameters_sample.yml
  field='${CES_SICES_DATABASE_PASS}'

  sed -i "s/$field/$password/g" $parameters

  mysql -u root -p$password -e 'CREATE DATABASE sices_solar;' > /dev/null 2>&1
  bash $CLI_PATH/ces-database-mirror $password

fi
